### ISSUE TITLE
Is there any special permission?

### ISSUE THREAD

**Issue by antoniomorais360** [nolanlawson/pretty-s3-index-html#3]
oops.. sorry. 
I am receiving the error below:

"Skip to content This repository Search Pull requests Issues Gist @antoniomorais360 Watch 1 Star 18 Fork 4 nolanlawson/pretty-s3-index-html Branch: master pretty-s3-index-html/index.html 55610b on 4 Sep @nolanlawson nolanlawson improve speed, reliability 1 contributor RawBlameHistory 191 lines (156 sloc) 5.49 KB"

**Comment by antoniomorais360** [comment]
Well, now the only error is that is not showing the directory, only files :/

**Comment by antoniomorais360** [comment]
The folder is "Unknown", like in your example. It is just a bug. Any chance to fix it?

**Comment by nolanlawson** [comment]
Hm, it works for me as long as I set the permissions on everything to be public-readable: https://s3.amazonaws.com/nolanlawson/index.html

**Comment by antoniomorais360** [comment]
Look back to your link There are some "Unknown" in your link too :)

**Comment by namebrandon** [comment]
I'm seeing the same issue, root level directories within the bucket are not showing up. Any ideas?

**Comment by nolanlawson** [comment]
I'm not maintaining this tool anymore; sorry about that.

**Comment by Hayorti** [comment]
For future reference, and since this was actually a simple solution, the problem is caused by a mismatch between the XML output and the RegExp being used to find folders.

Line 57 should be changed from:
var FOLDER_PATTERN = new RegExp('_\$folder\$$');
to:
var FOLDER_PATTERN = new RegExp('\/$');

The current XML output of S3 bucket contents simply has a trailing "/" after the name of a key if it is a directory, which is what the new RegExp checks for... A "/" as the last character.

**Comment by nolanlawson** [comment]
Cool, can you open a pull request?

**Comment by nolanlawson** [comment]
This project is archived, so I am closing this issue. Thanks!
